### ISSUE TITLE
Changing parser to ANTLR

### ISSUE THREAD

**Issue by Marti2203** [snekkylang/snekky#1]
Hello,
I saw this project randomly and saw the lexer and parser were handwritten. I am interested in helping out to make them generated by [ANTLR](antlr.org). The only thing is a little yakshave - making a generator for Crystal.

**Comment by SenkJu** [comment]
Thank you very much for the offer but Snekky is just a fun, little side-project for me. When I began working on it, I knew absolutely nothing about how to make a programming language and that becomes quite obvious when looking at its code. I came up with pretty much everything myself. For that reason I prefer the lexer and parser to stay handwritten. My goal is not to develop a language suitable for daily use but to try and figure out the required concepts myself.

**Comment by Marti2203** [comment]
Okay! Cool! That is a fun... Good luck and have fun :)
I will close the issue
