### ISSUE TITLE
Add support for string escaping

### ISSUE THREAD

**Issue by MrWouterNL** [snekkylang/snekky#10]
Currently, string escaping isn't a feature in this beautiful programming language, adding that feature would be really useful when working with strings.

``Sys.print("Hello \"world");`` should return ``Hello "World``, but instead gives an error

**Comment by SenkJu** [comment]
Thanks for suggesting. I added the ability to escape " in https://github.com/snekkylang/snekky/commit/69429d7b794aa8c68272700f2f0725d5d79de2e2.
